name: 'Run vim for vimhelp to html'
description: 'Generate HTML vim doc help'
author: 'Tsuyoshi CHO <Tsuyoshi.CHO+develop@Gmail.com>'
inputs:
  FOLDER:
    description: "Build work directory"
    default: 'build'
    required: false
  BACKGROUND:
    description: "HTML background type(light and dark)"
    default: 'light'
    required: false
  COLORSCHEME:
    description: "HTML colorscheme type(as vim built-ins' and github)"
    default: 'github'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.folder }}
branding:
  icon: 'alert-octagon'
  color: 'blue'
